const {Redis}=require('@upstash/redis');
const CREDIT_TTL_SECONDS=60*60*24*365;
const PACK_CREDITS=5;
let redis;
function isCreditStoreConfigured(){return Boolean((process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL)&&(process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN));}
function getRedis(){if(!isCreditStoreConfigured())throw new Error('Credit storage is not connected');redis||=new Redis({url:process.env.UPSTASH_REDIS_REST_URL||process.env.KV_REST_API_URL,token:process.env.UPSTASH_REDIS_REST_TOKEN||process.env.KV_REST_API_TOKEN});return redis;}
async function pingCreditStore(){if(!isCreditStoreConfigured())return false;try{return await getRedis().ping()==='PONG';}catch{return false;}}
function assertSessionId(sessionId){if(!/^cs_(?:test_|live_)?[A-Za-z0-9]{20,}$/.test(String(sessionId||'')))throw new Error('Invalid credit pass');return String(sessionId);}
function keys(sessionId){const id=assertSessionId(sessionId);return {pack:`hsc:credits:${id}`,used:`hsc:credits:${id}:used`};}
async function ensureCreditPack(session){const {pack}=keys(session.id);const script=`if redis.call('EXISTS', KEYS[1]) == 0 then redis.call('HSET', KEYS[1], 'remaining', ARGV[1], 'total', ARGV[1], 'email', ARGV[2], 'created_at', ARGV[3]); redis.call('EXPIRE', KEYS[1], ARGV[4]); end; return tonumber(redis.call('HGET', KEYS[1], 'remaining') or '0')`;return Number(await getRedis().eval(script,[pack],[String(PACK_CREDITS),session.customer_details?.email||'',String(Date.now()),String(CREDIT_TTL_SECONDS)]));}
async function getCreditPack(sessionId){const {pack}=keys(sessionId);const data=await getRedis().hgetall(pack);if(!data)return null;return {remaining:Number(data.remaining||0),total:Number(data.total||PACK_CREDITS),email:data.email||null};}
async function reserveCredit(sessionId,requestId){if(!/^[a-f0-9-]{20,64}$/i.test(String(requestId||'')))throw new Error('Invalid generation request');const {pack,used}=keys(sessionId);const script=`if redis.call('EXISTS', KEYS[1]) == 0 then return {-1, 0, 0} end; local remaining=tonumber(redis.call('HGET', KEYS[1], 'remaining') or '0'); if redis.call('SISMEMBER', KEYS[2], ARGV[1]) == 1 then return {remaining, 1, 1} end; if remaining <= 0 then return {0, 0, 0} end; remaining=redis.call('HINCRBY', KEYS[1], 'remaining', -1); redis.call('SADD', KEYS[2], ARGV[1]); redis.call('EXPIRE', KEYS[1], ARGV[2]); redis.call('EXPIRE', KEYS[2], ARGV[2]); return {remaining, 1, 0}`;const result=await getRedis().eval(script,[pack,used],[String(requestId),String(CREDIT_TTL_SECONDS)]);return {remaining:Number(result[0]),allowed:Number(result[1])===1,retry:Number(result[2])===1};}
async function releaseCredit(sessionId,requestId){const {pack,used}=keys(sessionId);const script=`if redis.call('SREM', KEYS[2], ARGV[1]) == 1 then return redis.call('HINCRBY', KEYS[1], 'remaining', 1) end; return tonumber(redis.call('HGET', KEYS[1], 'remaining') or '0')`;return Number(await getRedis().eval(script,[pack,used],[String(requestId)]));}
module.exports={PACK_CREDITS,isCreditStoreConfigured,pingCreditStore,ensureCreditPack,getCreditPack,reserveCredit,releaseCredit};
